source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/HannahZheng/HannahUIKit.git'

use_frameworks!

target 'HannahUIKit_Example' do
  pod 'HannahUIKit', :path => '../'

  target 'HannahUIKit_Tests' do
    inherit! :search_paths

    
  end
end
